threads: 15  # number of threads to run the bot
eth_rpc: https://rpc.immutable.com  # Ethereum RPC URL

delay_between_quests: 5  # delay between quests in seconds
delay_between_quests_verification: 5  # delay between quests verification in seconds
delay_between_chests: 5  # delay between chests in seconds

